organisms-footer
U03KTGYJS1E/mion-frontend-basic-last-assignment pull request #13
Opened 2023-08-16 02:35 UTC by U03KTGYJS1E

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

http://localhost:6006/?path=/story/organisms-footer--footer

現在アイコンは未調整です。

2023-08-28 11:32 UTC, MinamiHotta reviewed
よくFigmaと制作物を見比べて修正してみましょう！
また、同時に多くのパーツを作成している分、同じことを指摘されることもあると思いますが、気づいたらすぐに他のパーツにも同様の修正をかけるようにしましょう！

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +  <div class="bottom">
Copyright用のタグがあるので、探してみてください

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +<div class="container">
最上位は`footer`クラスにしましょう。修正方法は、plansと同様です。

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +      </p>
住所用のタグがあるので、探してみてください。

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +      <i class="fas fa-rss"></i>
それぞれのアイコンも、リンク先に飛ぶ想定なので、aタグで囲みましょう。イメージは以下の通りです。
```suggestion
　  <a href="#">
　      <i class="fab fa-facebook-f"></i>
　  </a>
```

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +  <div class="bottom">
`bottom`というクラス名だと分かりにくいので`copyright`などがオススメです

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +      </p>
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/6c4aeca0-5174-4f89-95c4-086f78943f53)
また、pタグのデフォルトの16pxは消すようにしましょう。詳細は、Figmaを確認してください。

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.html
> +  </nav>
並びがFigmaと異なるので、面談でのアドバイスを参考に、直してみてください。
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/52536ada-b511-49c8-b83e-681810bcc5ae)
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/1b27c45a-3e38-48d8-8793-c73e7bf763d4)

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.scss
> +      }
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/b112196a-0a71-4fbc-9170-3d8808a92f81)
liタグまわりで無理やりサイズ調整した感があり、見本よりもやや余白が大きくなってしまっているので、gap等をうまく活用してサイズ調整してみましょう。

2023-08-28 11:32 UTC, MinamiHotta commented on src/components/organisms/footer/footer.scss
> +      }
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/dfd4fc9e-80e1-44ff-b9da-b90d8c77e0b8)
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/67435a8e-d0e2-41a6-b256-7e3788c8323c)
lgのときは逆にやや狭いです

2023-09-12 05:20 UTC, ssshun3 reviewed
大体goodです！細かいところも含めて５点修正お願いします！コード部分に記述したので確認お願いします。

- [x] containerに関して+クラス名
- [x] line-heightの追加に関して+クラス名
- [x] nav内の隙間に関して
- [ ] 画面幅のpaddingに関して
- [ ] 不要なコメントに関して

2023-09-12 05:20 UTC, ssshun3 commented on src/components/organisms/footer/footer.html
> +<div class="fotter container">
おそらくfotter→footerですかね？もし変更する場合はnavタグで使用しているクラス名(footer)を変更するかスタイルの当て方を変更する必要があります。
それと、`container`は左右に余白を作成するために使用しますが今回の場合は横幅いっぱいに広がってほしいので今回は必要ないです。

2023-09-12 05:20 UTC, ssshun3 commented on src/components/organisms/footer/footer.scss
> +    @media screen and(max-width:$breakpoint-lg) {
max-widthは～以下の時にスタイルを適用することを表すメディアクエリです。そのため今回の場合画面幅がlg以下の時に`padding: 52px 20px;`のスタイルが適用されることになります。しかしfigmaを確認するとbreakpointはlgではないことがわかると思います。ここ以外のメディアクエリも同様に修正お願いします。
またスタイルの適用もおそらく意図しているものとは画面幅で逆になっていると思います。このようなスタイルミスは開発者ツールを使用して想定しているスタイル（今回はpadding）になっているか確認できまるので積極的に利用しましょう。

2023-09-12 05:20 UTC, ssshun3 commented on src/components/organisms/footer/footer.scss
> +    //justify-content: center;
必要なさそうであれば消しちゃいましょう。ほかのコメント部分も同様です。

2023-09-12 05:20 UTC, ssshun3 commented on src/components/organisms/footer/footer.html
> +      <asress>
おそらくasress→addressですかね？
他に文章部分に関してline-heightの設定をお願いします。
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/110015394/3e4c196b-aa0d-4bb7-b54e-881dfc2d04b2)

2023-09-12 05:20 UTC, ssshun3 commented on src/components/organisms/footer/footer.html
> +  </nav>
画面幅s以下に関して今使用しているcssではgapなどは使用できなさそうなのでpaddingなどで隙間を調整しましょう。
例えば

- `li`タグに`padding-bottom:8px`を使用して４番目と８番目にはスタイルを無効化する
または
- `li`タグに`padding-bottom:8px`を使用してnavタグの`padding-bottom`だけ8pxにして他は16pxのままにする（    `padding: 16px 16px 8px 16px;`）
後者のほうが修正する手間が少なそうですね。
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/110015394/2559c356-86cb-40b1-946d-6a2b014c3ef7)

2023-09-18 03:43 UTC, U03KTGYJS1E commented on src/components/organisms/footer/footer.html
> +  </nav>
2つ目も試したのですがmd 以上になった時の調整が必要なため、今回は1つ目の方で調整しました。

2023-09-18 15:04 UTC, higashiji2000 requested changes
横並びの書き方を変えた場合、2列のレイアウトの書き方を変える必要があるかもしれません。
CSSのGridLayoutが参考になるかもしれません。
参考：https://shinonome-inc.notion.site/Grid-Layout-2-6b4637d544784396ade68d604971ce6c?pvs=4

2023-09-18 15:04 UTC, Higashiji commented on src/components/organisms/footer/footer.scss
> +    height: 44px;
```suggestion
    line-height: 1;
```
こうすることで、heightを固定しなくてもfigmaと同じ見た目になります。
デフォルトでは line-height がついてしまっているを、figmaの方に合わせfont-sizeと同一にしています。

2023-09-18 15:04 UTC, Higashiji commented on src/components/organisms/footer/footer.scss
> +      column-gap: 8px;
```suggestion
      display: flex;
      justify-content: center;
```
columnを使うとそれぞれのカラムが等幅になってしまうため、現在の書き方ではmd以下の時のFigmaのデザインを再現することができません。
columnのほうがスマートにかけるのは確かですが、横並びのレイアウトはflexboxで実装しましょう。

2023-09-18 15:04 UTC, higashiji2000 commented on src/components/organisms/footer/footer.scss
> +      }
```suggestion
      li {
      padding: 0 8px;
      &:not(:last-child) {
        border-right: 1px solid #black;
      }
        @media screen and(max-width: $breakpoint-md) {
          text-align: start;
          padding-bottom: 0 0 8px 0;
          border: 0;
        }
      }
```
区切り線の指定はこちらに移動させましょう。

2023-09-18 15:04 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +      <img src="../../../img/footer.png" alt="" />
```suggestion
      <img src="../../../img/footer.png" alt="Switch" />
```
画像で文字を表現している際は、その内容を `alt` 属性に入れておきましょう！

2023-09-20 14:59 UTC, higashiji2000 approved these changes
LGTMです！
修正のスピードや正確さが上がってきててすごく成長を感じます🛸

2023-09-20 14:59 UTC, higashiji2000 commented on src/components/organisms/footer/footer.html
> +<div class="footer">
```suggestion
<footer class="footer">
```
セマンティック要素を意識的に使えるとより良くなると思います 👍

2023-09-20 16:03 UTC, merged