Templates-newsAndEvents
U03KTGYJS1E/mion-frontend-basic-last-assignment pull request #14
Opened 2023-09-24 15:15 UTC by U03KTGYJS1E

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-09-29 02:11 UTC, MinamiHotta commented
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/eaff98fb-5350-40ba-b982-40dba4fa708b)
画面smのとき`margin-bottom: 35px;`は不要です！

2023-09-29 02:17 UTC, MinamiHotta commented
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/9b8ac799-da5c-4faf-9074-a6e9c83899e4)
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/f9617f37-983c-462a-98f3-206a26751d9c)

Figma通りにうまく余白等含め実装できている（1枚目・mionさんのもの）のですが、この課題では「横並びになったときにnewsとeventの縦幅が揃う」（2枚目・Figmaのお手本）ことが求められています。ただ、現状あまりにもFigmaの数字と、その実装結果が乖離していて近づけるのが難しいので、こちらは二次レビューアーさんに判断いただきたいと思います。

2023-09-29 02:28 UTC, MinamiHotta commented
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/243fba40-423d-4bf6-87bd-be32df0f856f)
画面サイズmdの段階で、1枚目の画像のようになってほしいです。
ですので、mdのときに
2枚目：タイトルの文字の大きさを小さく
3枚目：タイトルの文字の大きさを小さく＆写真をなしに
の2点を修正ください。

![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/4430957b-c2f7-41cd-9dc3-2d30dfb6f581)
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/c9980447-162a-4f0b-92f7-993043e69a6f)

2023-09-29 02:30 UTC, MinamiHotta commented
タグの使い分けがとても上手です！！！
コード自体はきれいで問題ないと思います。

2023-10-07 01:27 UTC, MinamiHotta commented
> ![image](https://user-images.githubusercontent.com/104500220/271457649-243fba40-423d-4bf6-87bd-be32df0f856f.png) 画面サイズmdの段階で、1枚目の画像のようになってほしいです。 ですので、mdのときに 2枚目：タイトルの文字の大きさを小さく 3枚目：タイトルの文字の大きさを小さく＆写真をなしに の2点を修正ください。
> 
> ![image](https://user-images.githubusercontent.com/104500220/271457708-4430957b-c2f7-41cd-9dc3-2d30dfb6f581.png) ![image](https://user-images.githubusercontent.com/104500220/271457756-c9980447-162a-4f0b-92f7-993043e69a6f.png)

こちら，smとmdは見た目が同じになってほしいので，breakpointを変えて，現在のsmと同じ見た目になるようmdを調整してください！

2023-10-08 09:28 UTC, MinamiHotta commented
二次レビューアーさんへ
[こちら](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/pull/14#issuecomment-1740223531)確認お願いします！

2023-10-09 15:14 UTC, Higashiji requested changes
[こちら](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/pull/14#issuecomment-1740223531)に関してですが、Figma通りにNewsとEventの高さが揃うように修正お願いします！


https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/83479175/31141b02-e4e9-4f99-9d53-180b316b1475

`time` 要素がinlineであることに起因して謎の余白が生じてしまっているようなので、こちらだけ修正いただければ少しは揃えやすくなるかと思います。
揃えるのを優先した結果、Figma の値と少しずれるぶんには問題ありません。

2023-10-09 15:14 UTC, Higashiji commented on src/components/templates/newsAndEvents/newsAndEvents.scss
> +  padding: 0rem 1rem;
```suggestion
```
余白は `container` で管理するため、ここからは省いてしまってOKです。
（Figmaで変な値になっていたならこちらのミスです 🙏 ）

2023-10-09 15:14 UTC, Higashiji commented on src/components/templates/newsAndEvents/newsAndEvents.scss
> +    padding: 56px 0px;
現状、`.container` に設定された横方向の padding を0 で上書きしてしまっています。
横幅が仕様より狭くなってしまっているので、修正しましょう。

```suggestion
    padding-top: 56px;
    padding-buttom: 56px;
```

こうすると横方向のpaddingは無指定になるので、 `.container` の方に書いてある内容が適用されます。
もしくは

```suggestion
    padding-block: 56px;
```

縦方向のpaddingを設定する [padding-block](https://developer.mozilla.org/ja/docs/Web/CSS/padding-block)を使ってもよいですね

2023-10-09 15:14 UTC, Higashiji commented on src/components/templates/newsAndEvents/newsAndEvents.scss
> +        width: 88%;
```suggestion
      flex: 1;
    }
    .events {
      flex: 1;
      @media screen and (max-width: $breakpoint-lg) {
```

現状でも見た目は問題ないので修正不要ですが、flexboxを使って要素を均等に並べるのであれば、それぞれに `flex: 1;` を設定し、余白は `gap` プロパティで管理するというのがスッキリかけておすすめです。

参考：https://www.notion.so/shinonome-inc/Flexbox-1-e28e57a82d004507bfef1179b8fd6845?pvs=4

2023-10-09 15:14 UTC, Higashiji commented on src/components/templates/newsAndEvents/newsAndEvents.html
> +          <time>2018.06.20</time>
```suggestion
          <time datetime="2018-06-20">2018.06.20</time>
```
time属性は決まった書式しか受け入れていないので、仕様に厳密に則るとするとこのように `datetime` 属性を設定することになります。
ただ News コンポーネントは実装済みなので一旦修正は不要です。

2023-10-10 05:31 UTC, U03KTGYJS1E commented on src/components/templates/newsAndEvents/newsAndEvents.scss
> +        width: 88%;
flex=1を試したところ、画面幅medium以外のときに親要素からはみ出してしまい調整の方法が分からなかったので、そのままにしました。

2023-10-15 08:18 UTC, higashiji2000 commented on src/components/templates/newsAndEvents/newsAndEvents.scss
> +        width: 88%;
なるほど！
どこかでwidthを固定値に設定していたり、 `flex` を指定している要素がフレックスアイテムではないなどの原因が考えられそうですね :thinki

2023-10-15 08:22 UTC, higashiji2000 requested changes
きちんと高さが修正できていていい感じです！
細かい指摘も反映できていて素晴らしいです。

一点だけ修正お願いします

---

![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/83479175/efef7d1d-b6c3-4a00-a9c2-efe5570d57f3)

画像のmarginによって左右のmoreの部分に高さの差が存在してしまっています。
こちらのmarginをなくしてしまってください。

2023-10-17 05:31 UTC, U03KTGYJS1E commented on src/components/templates/newsAndEvents/newsAndEvents.scss
> +        width: 88%;
今回幅を調整した箇所を無効化させてみたのですが上手くいきませんでした。恐らく以前作成した要素に問題があるようなので今回はflexでない方法にし今後の作成の際にflexを使いたいと思います

2023-10-18 05:26 UTC, higashiji2000 approved these changes
LGTMです！
コメントへの返信が丁寧で信頼感がすごいです🥳

2023-10-18 05:40 UTC, merged