button(html,scss,stortbookの一通り)1回目
U03KTGYJS1E/mion-frontend-basic-last-assignment pull request #2
Opened 2022-10-29 12:21 UTC by U03KTGYJS1E

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2022-10-30 13:28 UTC, AyumuTaoka commented on src/components/atoms/button/button.html
> +<button class="atoms-button">コンセプト</button>
今回はaタグで書くように課題ページに指定があるので修正お願いします！
またクリック時の遷移先も書くようにしましょう！（html aタグで調べてみると色々出てくると思います！）
![スクリーンショット 2022-10-30 22 02 03](https://user-images.githubusercontent.com/104242534/198879886-5b3218c5-6ab6-44e7-8132-e22f3d4e416e.png)

2022-10-30 13:28 UTC, AyumuTaoka commented on src/components/atoms/button/button.scss
> +}
.atoms-button {
  color: white;
  font-size: $fontsize-example;
  background-color: $black;
  transition: background-color 0.2s ease;
  & :hover {
    background-color: $orange_bistre;
  }


と書くことで記述量が少なくなり読みやすくなるというのがscssの利点の１つであるので、
特にこだわりがなければこちらの書き方の方がいいかもしれません！
（スペース等ずれていますので課題ページの"Storybookの使い方、Sassについて"を参考にしてみて下さい！）
以下URL
https://shinonome.io/frontend-basic/lastAssignment/storybook_sass/

2022-10-30 13:28 UTC, AyumuTaoka commented on src/components/atoms/button/button.scss
> +  }
ブレイクポイントについてですが、使うのはmin-widthかmax-widthのどちらかにする方が読みやすいので多くみられます。
また、どちらかにすることで、分岐がa以上、b以上、それ以外というようにでき、シンプルで読みやすい書き方にできるので調べてみて下さい！
さらに、共通する部分はブレイクポイントの指定の外で書くことで１度書くだけで良くなります！

2022-12-03 14:02 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/205444616-054d9193-f778-4cd4-81fe-abbca5c54f33.png)
こちら、hoverしたときに青い文字が出てきてしまっているので、消すためのcssを書いてみてくださいー！
🔍aタグ　リンクの色を変えない
で検索してみましょ✨

2022-12-03 14:08 UTC, MinamiHotta reviewed
あともうちょい！
hover時のテキストの色の変化に付随して、もう一点修正箇所が出てくるのでいろいろ試してスタイル直していきましょう✨

2022-12-03 14:08 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
> +  flex-direction: row;
デフォルトがrowなので書かなくてOKです！

2022-12-03 14:08 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
> +  top: 24px;
topとleftは二つ以上要素が重なった時の位置決めで用いることが多いため、今回は不要です！

2022-12-03 14:08 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
> +  }
こちらのサイズですと、heightの値も変わっていると思うので、Figma確認して書き足しましょうー！

2022-12-03 14:08 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
> +  font-size: $fontsize-example;
こちら、デフォルトがこのフォントサイズだと思うので記述不要です！

2022-12-04 10:55 UTC, MinamiHotta reviewed
あともうちょいです！
コミットメッセージはばっちりなので、今度はレビューに対してリアクションの絵文字つけてみましょ🔥

2022-12-04 10:55 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
> +  position: absolute;
position:absolute;　消して大丈夫です！

2022-12-04 10:55 UTC, MinamiHotta commented on src/components/atoms/button/button.scss
> +  padding: 0px 16px;
paddingもなくて大丈夫です！

2022-12-04 10:57 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/205486700-79795723-c2af-4d2b-bfef-7a0871a9f4e6.png)
ぜひここらへん、storybookの検証ツール使って「本当に必要かな？」とチェックを付け外しして試してみましょ！

2022-12-05 04:34 UTC, higashiji2000 requested changes
absoluteの削除だけお願いします！

2022-12-05 04:34 UTC, higashiji2000 commented on src/components/atoms/button/button.scss
> +  }
```suggestion
  @media screen and(max-width: $breakpoint-lg) {
    width: 150px;
  }
  
  @media screen and(max-width: $breakpoint-md) {
    height: 45px;
    width: 180px;
  }
```
順番は逆の方が望ましいです。
今回はデスクトップファーストで書いているので、画面幅が大きい時のスタイル→小さい時のスタイルの順番で書いていくと読みやすいコードになると思います。

2022-12-05 04:34 UTC, higashiji2000 commented on src/components/atoms/button/button.scss
> +  position: absolute;
これが残っていると、他のコンポーネントで使うのが難しくなるので、削除お願いします！

![image](https://user-images.githubusercontent.com/83479175/205550151-7b316e70-911b-49d5-bb24-adf888719d78.png)
↑こんな感じで他の要素と組み合わせた時に

![image](https://user-images.githubusercontent.com/83479175/205550201-289d067b-d5c5-43cf-aa8a-4a6d4d8e48cc.png)
↑こんな感じで重なってしまう

2022-12-21 13:02 UTC, caramelribon reviewed
1点だけ修正お願いします！

また検証ツールについてですが、こちらの資料は読んだことはありますでしょうか?
https://playground.wraptas.site/67db90c0263c44d58b966b5f23f69917

こちらの資料を読んで、検証ツールを使ってみてください！
またもし、この資料を読んだことがある、読んでもわからないときは遠慮なくもう一度仰ってください！！よろしくお願いします！
わからない場合は具体的にどこらへんがわからないかを言って頂けると助かります！

2022-12-21 13:02 UTC, caramelribon commented on src/components/atoms/button/button.scss
> +.atoms-button {
文字のサイズ(font-size)と高さ(line-height)の設定をお願いします！

2023-02-09 00:09 UTC, Higashiji approved these changes
LGTM 🐪

2023-02-11 09:59 UTC, merged