molecules/message1回目
U03KTGYJS1E/mion-frontend-basic-last-assignment pull request #3
Opened 2023-02-04 12:13 UTC by U03KTGYJS1E

## セルフチェック
- [ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ] 記述の重複はないか

2023-02-08 14:59 UTC, AyumuTaoka commented on src/components/molecules/message/message.html
> +  <h2 class="explain">説明テキスト</h2>
説明テキストは見出しではないのでhタグを使うのは適切でないと思います。

2023-02-08 15:03 UTC, AyumuTaoka commented
h1タグを使うことによって自動でpadding-bottomが付いてしまっています。
また、line-hieghtがfigmaと違うので確認お願いします
![スクリーンショット 2023-02-09 0 01 35](https://user-images.githubusercontent.com/104242534/217567525-d7b3c66a-cd29-4558-b873-9f16a3749807.png)

2023-02-08 15:05 UTC, AyumuTaoka commented on src/components/molecules/message/message.scss
> +  position: relative;
position: relative;はなくても大丈夫なので確認お願いします。

2023-02-13 08:11 UTC, tomu-fujikawa reviewed
コメントしました！

2023-02-13 08:11 UTC, tomu-fujikawa commented on src/components/molecules/message/message.html
> +  <p style="margin: 0" class="explain">説明テキスト</p>
2,3行目の`margin:0`は両方ともなくて大丈夫です！
`h1`タグはページ全体で１回だけ使うものなのでただの１パーツのmessageでは使用しないようにしましょう！
なので`h2`以降のhタグを指定してください！
`h`タグを使用する影響でfont-weightが`400`ではなくなるのでscssの方で`font-weight:400;`を指定してください！

2023-02-18 06:48 UTC, higashiji2000 requested changes

2023-02-18 06:48 UTC, higashiji2000 commented on src/components/molecules/message/message.html
> +  <p style="margin: 0" class="explain">説明テキスト</p>
```suggestion
  <h2 class="title">タイトルテキスト</h1>
  <p class="explain">説明テキスト</p>
```
tomuさんのご指摘の通り、h1タグはページ全体で一度しか使ってはいけないことになっているので、今回のように使い回す前提のコンポーネントには不向きです。
参考：https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements

また、styleタグは使用せず、CSSで見た目を調節するようにしましょう。

2023-02-18 06:48 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +    font-family: $fontfamily-mincho;
```suggestion
  .title {
    margin: 0;
    font-family: $fontfamily-mincho;
```
こういう感じです

2023-02-18 07:08 UTC, higashiji2000 approved these changes
LGTMです🏯

2023-02-18 07:12 UTC, merged