organisms-about
U03KTGYJS1E/mion-frontend-basic-last-assignment pull request #9
Opened 2023-08-14 04:01 UTC by U03KTGYJS1E

## セルフチェック
- [〇] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [〇] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [〇] 記述の重複はないか

http://localhost:6006/?path=/story/organisms-about--about

2023-08-26 15:13 UTC, MinamiHotta reviewed
修正お願いします！BootCampなどを有効活用し、他のパーツもスピーディーに完成させていきましょう！

2023-08-26 15:13 UTC, MinamiHotta commented on src/components/organisms/about/about.html
> +
5,9行目の空白行は消すようにしてください

2023-08-26 15:13 UTC, MinamiHotta commented on src/components/organisms/about/about.scss
> +}
explainの部分の、下の余白は不要なので、削除してください
[1枚目]：見本のFigma
[2枚目]：現状のstorybook
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/39391d5a-19c3-49e9-8ce8-8e3718d22ff9)
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-last-assignment/assets/104500220/89facb60-10dc-431c-9295-8f04a496a70f)

2023-08-26 15:13 UTC, MinamiHotta commented on src/components/organisms/about/about.scss
> +    }
サイズ設定、簡潔にできていてナイスです◎

2023-08-26 15:13 UTC, MinamiHotta commented on src/components/organisms/about/about.scss
> +}
```suggestion
.top-message {
  width: 100%;
  background-color: $white_smoke;
  .title {
  color: $orange_bistre;
  }
  .explain {
  color: $black;
  }
}
```
厳密にsassの書き方に習うならば、上記のような入れ子構造になります。さらに厳密なことを言うと、`.container`の中に`.imgContent`以下のすべての記述が入る構造になります。
ただし、最近の潮流として入れ子にせずベタでcssを書くことも増えているため、この点に関しては修正してもしなくてもOKです。

2023-08-26 15:13 UTC, MinamiHotta commented on src/components/organisms/about/about.html
> +  <div class="content imgContent">
`content`クラスは、別のパーツで定義している、または`container`のようにデフォルトで用意されている万能なクラスなのでしょうか...？もしそうなら残していただいて構わないのですが、不要ならば消してしまってください！（10行目も同様です）

2023-08-27 05:59 UTC, higashiji2000 requested changes

2023-08-27 05:59 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +  margin: 100px 0px;
```suggestion
  padding-top: 100px;
  padding-bottom: 100px;
```
`cards` と同様にmarginは `.container` のものを使います。
上下に余白を付けたいので、`padding` を設定しましょう。
`padding: 0 100px` としないのは、 `.container` にもとからついている横方向の `padding` を上書きしないためです。

2023-08-27 05:59 UTC, higashiji2000 commented on src/components/organisms/about/about.html
> +  <div class="imgContent">
```suggestion
  <div class="img-container">
```
クラス名はケバブケースにしてください。
こんな感じにするとより直感的なクラス名になるかと思います！
参考：https://www.wakuwakubank.com/posts/804-it-naming-convention/

2023-08-27 05:59 UTC, higashiji2000 commented on src/components/organisms/about/about.scss
> +  }
```suggestion
  @media screen and (max-width: $breakpoint-lg) {
    padding-top: 40px;
    padding-bottom: 40px;
  }
```
こちらも上下にのみpaddingをつけたいので、こんな感じに修正お願いします！

2023-08-27 06:10 UTC, merged